version: "3.3"

services:
  app:
    build: .
    command: bash start.sh
    restart: on-failure
    ports:
      - "256:256"
      - "8268:8268"
networks:
  default:
    external: true
    name: network11